### ISSUE TITLE
"Buffer is read-only" errors due to delete-trailing-whitespace in git-rebase-mode

### ISSUE THREAD

**Issue by hlissner** [editorconfig/editorconfig-emacs#167] opened 2018-06-30 11:02 UTC
I have a root editorconfig with this in it:

```
[*]
trim_trailing_whitespace = true
```

This issue was mentioned in magit/magit#3500. When I invoke a git-rebase-mode buffer through magit, editorconfig adds `delete-trailing-whitespace` to `write-file-functions`. Because git-rebase-mode is a special mode and, thus, read-only, when you move to commit or abort the rebase, it tries to write the file first, causing `delete-trailing-whitespace` to throw a "Buffer is read-only" error that stops everything in its tracks.

Adding `git-rebase-mode` to `editorconfig-exclude-modes` does not work because `editorconfig-mode-apply` is triggered first while the buffer is in fundamental-mode (and passes its checks). When it eventually changes to git-rebase-mode, there's no logic to remove delete-trailing-whitespace from write-file-functions. Also, `write-file-functions` has the `permanent-local` property, so its local value doesn't get killed in between major-mode changes.

I have two workarounds:

```elisp
(add-to-list 'editorconfig-exclude-regexps "/git-rebase-todo\\'")

;; or

(defun editorconfig-disable-trim-whitespace-in-read-only-buffers (props)
  (when (and buffer-read-only (gethash 'trim_trailing_whitespace props))
    (remove-hook 'write-file-functions #'delete-trailing-whitespace :local)))
(add-hook 'editorconfig-custom-hooks #'editorconfig-disable-trim-whitespace-in-read-only-buffers)
```

I'm not sure what the right way to address this is, but here are some ideas:

+ `editorconfig-mode-apply` could refuse to apply to buffers in fundamental-mode
+ A hypothetical `editorconfig-mode-undo` function could restore editorconfig's changes should the buffer fail to meet editorconfig-mode-apply's criteria, if necessary.
+ `delete-trailing-whitespace` could be added to `before-save-hook` instead of `write-file-functions`, because git-rebase (and I presume most special modes of this sort) bypass the saving mechanism and simply write things out (or so I hope).
+ An `editorconfig-delete-trailing-whitespace` function could replace `delete-trailing-whitespace`, that no-ops silently if `buffer-read-only` is non-nil.

Hope that helps!

**Comment by 10sr** [comment] 2018-07-08 09:38
@hlissner  Thanks for reporting!

I couldn't reproduce the problem (I tried git-rebase-mode with `trim_trailing_whitespace = true` in my test repository, and successfully save the changes...), but I made some changes that hopefully fix this.
I'd glad if you could check the latest package and see things solved! (note that it will work only when `git-rebase-mode` is *not* included in `editorconfig-exclude-modes`)

**Comment by 10sr** [comment] 2019-10-23 04:54
Closing because there are no update recently.
Please feel free to reopen issue if the problem still exists.

**Closed by 10sr** 2019-10-23 04:54 UTC

**Comment by hlissner** [comment] 2019-10-23 05:02
Ah, sorry for not following up. The issue has not resurfaced since, so I think it is safe to say this is resolved. Thanks!
