### ISSUE TITLE
file coding from .editorconf is not applied

### ISSUE THREAD

**Issue by MathanGeurtsen** [editorconfig/editorconfig-emacs#232] opened 2020-11-03 12:22 UTC
Hey, I've got a project where I want the file encoding to be set to utf-8 by the editorconfig, which I'm not succeeding at. 

 `editorconfig-display-current-properties` shows that editorconfig is picking up that the charset should be utf-8, and C-h C RET shows that "Coding system for saving this buffer:
  U -- utf-8-dos (alias: mule-utf-8-dos cp65001-dos)", but the characters are still wrong, for example a test.txt file with just the character "β" in it, which emacs will display as "Î²", unless I put a coding comment like "# -*- coding: utf-8 -*-" at the top, in which case it is displayed correctly. 

this is "GNU Emacs 27.1 (build 1, x86_64-w64-mingw32)
 of 2020-08-21" on windows. 

I've verified with a --no-init loading just editorconfig and an .editorconfig file that looks like this:
```
root = true

[*.txt]
charset = utf-8

```

**Comment by 10sr** [comment] 2020-11-22 18:05
I cannot reproduce your problem on MacOS (I do not have a windows environment with Emacs...), but I anyway created a PR which might solve this.
Could you try this `revertforcofingsystem` branch?

**Comment by 10sr** [comment] 2021-01-08 04:31
Now I merged the PR to master 🙌

**Comment by MathanGeurtsen** [comment] 2021-01-08 15:39
Hey, apologies for not getting back to this! 

With the latest version I can't reproduce the error anymore, and it works now in my project as well, so it's fixed, thank you so much!

**Comment by 10sr** [comment] 2021-01-12 04:28
Thanks! 👍  
Closing this now

**Closed by 10sr** 2021-01-12 04:28 UTC
