### ISSUE TITLE
Section ordering has side effects

### ISSUE THREAD

**Issue by pdex** [editorconfig/editorconfig-emacs#72] opened 2016-03-08 18:16 UTC
This config file has tabs for everything:
```ini
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
indent_size = 2
indent_style = space
tabwidth = 2

# Tab indentation (no size specified)
[Makefile]
indent_style = tab
```

Where as this config file only has tabs for Makefiles

```ini
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

# Tab indentation (no size specified)
[Makefile]
indent_style = tab

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
indent_size = 2
indent_style = space
tabwidth = 2
```

I'm using the latest version on MELPA:
editorconfig 0.7.3
editorconfig-core 0.6.2
editorconfig-fnmatch 0.6.2

**Comment by xuhdev** [comment] 2016-03-08 20:58
This is expected, as editorconfig interprets the conf files from top to bottom and overrides previous conf if exists.

**Comment by pdex** [comment] 2016-03-09 20:04
Is this documented anywhere? I was expecting the wildcard to be the base value and the Makefile to be the specialized case.

**Comment by xuhdev** [comment] 2016-03-09 20:19
From [here](http://docs.editorconfig.org/en/master/editorconfig-format.html#format):

> Files are read top to bottom and the most recent rules found take precedence. If multiple EditorConfig files have matching sections, the rules from the closer EditorConfig file are read last, so properties in closer files take precedence.

**Comment by pdex** [comment] 2016-03-10 14:27
Sorry to keep bothering you about this. Just to be absolutely clear, I was working in a python file and it was using tabs for indents instead of spaces. Why would a rule for a Makefile affect a python file?

> All found EditorConfig files are searched for sections with section names matching the given filename. 

That sounds to me like the Makefile section shouldn't be matching my python file, and the [*] section should match.

**Comment by xuhdev** [comment] 2016-03-10 20:51
@pdex We cannot determine what glob is more specific than others; you can have much more complicated globs used here. This is not CSS, in which you can have a clear order of how specific a specifier is. Plus, this format is now quite clear. If we treat `[*]` differently, it can be more confused.

**Comment by xuhdev** [comment] 2016-03-11 00:36
@pdex I cannot reproduce this issue. Can you tell us more details? In addition, `tabwidth` should be `tab_width`.

**Comment by 10sr** [comment] 2016-03-11 02:10
@pdex I want to ask you some questions :bow: 

If you have other Emacs configurations, can you disable them all (except for editorconfig!) and try again?
Problem still remains?

When this happens, what is the result of `M-: (message "%S" (editorconfig-core-get-properties-hash))`

**Comment by pdex** [comment] 2016-03-11 15:20
@10sr I'll pair down my init.el and try to reproduce. There's a good chance that something I'm running may be conflicting with editorconfig-mode.

**Comment by 10sr** [comment] 2016-03-19 16:24
FYI I add a new function `editorconfig-display-current-properties`, which might be useful for this issue :smile: 
It is available from melpa (and not melpa stable yet, sorry).

**Comment by pdex** [comment] 2016-04-11 21:14
Sorry it took me so long to get back to you, I just got some time to dig into this again.
I stripped down my `init.el` to the bare minimum and the problem still exists.

# init.el
```
shadows:.emacs.d pdex$ cat init.el
;; -*- mode: lisp -*-

;; ELPA packages
(require 'package)

(setq package-archives '(("melpa" . "http://melpa.org/packages/")))

(package-initialize)

(require 'editorconfig)
(editorconfig-mode 1)
```

# .editorconfig
```
shadows:.emacs.d pdex$ cat editorconfigbug/.editorconfig
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
indent_size = 2
indent_style = space
tab_width = 2

# Tab indentation (no size specified)
[Makefile]
indent_style = tab
```

# Makefile
```
shadows:.emacs.d pdex$ cat editorconfigbug/Makefile
target: main.py
	python main.py
```

# Makefile properties hash
```
#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (end_of_line "lf" insert_final_newline "true" indent_size "2" indent_style "tab" tab_width "2"))
"#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (end_of_line \"lf\" insert_final_newline \"true\" indent_size \"2\" indent_style \"tab\" tab_width \"2\\
"))"
```


# python file
```
shadows:.emacs.d pdex$ cat editorconfigbug/main.py
def main():
	print "hello world"
```

# python properties hash
```
#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (end_of_line "lf" insert_final_newline "true" indent_size "2" indent_style "tab" tab_width "2"))
"#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (end_of_line \"lf\" insert_final_newline \"true\" indent_size \"2\" indent_style \"tab\" tab_width \"2\\
"))"
```

I'm currently working around this by appending the following section after `[Makefile]`

```
[*.py]
indent_style = space
```

**Comment by 10sr** [comment] 2016-04-12 03:26
Thanks! I'll look into it.

**Comment by lassik** [comment] 2016-04-26 17:56
I have the same problem with an almost identical `.editorconfig` file. I can't reproduce it with the latest `editorconfig-emacs` branch `fix72`. I'll try to reproduce it in a "live" situation and see if I can locate the bug (it's somewhere within `editorconfig-core-get-properties` or some function called by it).

**Comment by 10sr** [comment] 2016-05-02 12:25
@lassik @pdex I just submitted a PR that fixes the issue with my environment :point_up:
I'll merge it shortly, but I'd be glad if you try my branch ;)

**Comment by pdex** [comment] 2016-05-02 17:35
I'll give it a try!

**Comment by 10sr** [comment] 2016-05-03 11:25
I merged it, so the version with the fix will be soon available from MELPA (not MELPA stable, yet) :candy:

**Comment by pdex** [comment] 2016-05-03 22:48
I can verify that #92 fixed the issue for me.

**Comment by xuhdev** [comment] 2016-05-03 23:28
Thanks!

**Closed by xuhdev** 2016-05-03 23:28 UTC

**Comment by 10sr** [comment] 2016-05-04 01:41
Thank you very much for reporting this issue!!!

**Comment by pdex** [comment] 2016-05-04 03:02
Thanks to both of your for your time on this project and this issue!

**Comment by lassik** [comment] 2016-05-05 13:48
@10sr Somehow I can no longer reproduce the problem at all in my original environment. I updated to the latest `editorconfig-emacs` master with your fix and can't reproduce the problem with this version either, so I guess we can consider it solved. I understand your fix deals with caching/reuse of  editorconfig entries. That sounds like it may well be the culprit. Thank you for your effort!

**Comment by 10sr** [comment] 2016-05-06 05:03
No problem! Thanks!
